[default]
; M, the allow max len of perturbations, range [1, 4999]
max_perturb = 128
; Maximum number of iterations. If None it be max_iter_multi * max_len_perturbations
max_iterations = 2048
; Target accuracy threshold, must be in the range [0, 1].
target_acc = 0
; Number of top-k solutions to consider, range [1, 5000-M].
topk_num = 10
; Multiplier for tabu list length.
tabu_len_multi = 5
; Maximum number of dummy packets to insert in a delta_{i}.
max_dummy = 8
; Multiplier for solution length.
sol_len_multi = 4
; Denominator for candidate pool length of critical position.
cpm_len_den = 2
; Number of initial random solutions.
init_rd_num = 5
; Number of initial dummy packets (for more solusion search filed).
init_m_num = 8
; Length of exchange operations for random replace.
exch_len = 16
; Replacement rate for solutions, [0, 1].
repl_rate = 0.1
; Mutation rate for solutions, [0, 1].
muta_rate = 0.2
; Sampling rate for candidate pool, [0, 1].
smp_cpm_rate = 0.2
; Tolerance for early stopping, [0, 100].
toler = 30
; Multiplier for maximum iterations, [0, 1].
max_iter_multi = 8

[t1]
; M, the allow max len of perturbations, range [1, 4999]
max_perturbations = 128
; Maximum number of iterations. If None it be max_iter_multi * max_len_perturbations
max_iterations = 0
; Target accuracy threshold, must be in the range [0, 1].
target_acc = 0
; Number of top-k solutions to consider, range [1, 5000-M].
topk_num = 10
; Multiplier for tabu list length.
tabu_len_multi = 5
; Maximum number of dummy packets to insert in a delta_{i}.
max_dummy = 8
; Multiplier for solution length.
sol_len_multi = 4
; Denominator for candidate pool length of critical position.
cpm_len_den = 2
; Number of initial random solutions.
init_rd_num = 5
; Number of initial dummy packets (for more solusion search filed).
init_m_num = 8
; Length of exchange operations for random replace.
exch_len = 16
; Replacement rate for solutions, [0, 1].
repl_rate = 0.1
; Mutation rate for solutions, [0, 1].
muta_rate = 0.2
; Sampling rate for candidate pool, [0, 1].
smp_cpm_rate = 0.2
; Tolerance for early stopping, [0, 100].
toler = 30
; Multiplier for maximum iterations, [0, 1].
max_iter_multi = 8
